### PR TITLE
Allow to overload send() method

### PR DESCRIPTION
**Pull request by jjtmp**
This branch is based on "couple" branch so accepting this will also accept couple.

I'm not a C++ pro but probably I got all those keywords ("virtual") right. At least the compiler doesn't complain.

### CODE REVIEW

**Review by platisd — COMMENTED** [review]
Syntactically your change is correct. Idiomatically extending classes that are not pure virtual (i.e. `interfaces` in other languages such as Java) as well as protected member variables is considered a bad practice. ([C.133](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rh-protected))

But let's leave that aside for now. The real question is **why** should this change be merged? How does it help?

**Comment by jjtmp** [comment]
I just did this to keep Nokia_LCD.* as original as possible while playing with send() method. (Not using a typical version management system for that project). Not so important for me anymore.

**Comment by platisd** [comment]
I'd say if a user wants to extend the functionality this library, they should create their own class and inject this class into theirs.
Then they can use its API and do whatever they want with the new class' `send`.
If access to the "deeper" parts of the class is necessary, we can discuss about exposing them properly via its API.

**Comment by jjtmp** [comment]
Maybe sometimes it becomes necessary to overload send() or another method, but I agree that it may also never happen. With that words - closing.

**Comment by platisd** [comment]
Thanks for your contribution.
I will update the library version so it becomes available in Arduino IDE's library manager once I fix our broken CI, hopefully very soon.

**Pull request closed without merging**
